backend:
  name: github
  repo: jlkiri/phantasiai

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets
site_url: https://phantasiai.dev/

collections:
  - name: "posts"
    label: "Post"
    folder: "src/posts/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
